### PR TITLE
🐛 Ignore UdpSocket's WSAECONNRESET error on Windows

### LINKED ISSUE #391: Windows: WARN:smartdns::server::udp:36: error receiving message on udp_socket (and fix)
Only in windows it throws and UDP warning:
WARN:smartdns::server::udp:36: error receiving message on udp_socket: An existing connection was forcibly closed by the remote host. (os error 10054)

Here's the solution for windows only in rust:
https://github.com/shadowsocks/shadowsocks-rust/issues/262#issuecomment-633112782
You'll need to import the winapi package too: https://crates.io/crates/winapi

from notes:
Ignoring UdpSocket's WSAECONNRESET error
This is because UdpSocket::recv_from may return WSAECONNRESET
if you called UdpSocket::send_to a destination that is not existed (may be closed).
It is not an error. Could be ignored completely.
We have to ignore it here because it will crash the server.

I hope you add it soon
discussion: https://github.com/mokeyish/smartdns-rs/discussions/368

### PR DESCRIPTION
**Pull request by mokeyish**
closes #391

### CODE REVIEW

**Comment by mokeyish** [comment]
@chmichael Hi, I have changed to using windows_rs based on the code you provided. But I'm not sure if that solves the problem, can you help verify it?

Download link：https://github.com/mokeyish/smartdns-rs/actions/runs/11051243572

**Comment by chmichael** [comment]
Compiled and running it with 0 udp errors on windows! It works! 😄 
ps: i've used the version = "0.58" windows (there is 0.60 with many more fixes but not on cargo yet)

Thank you

**Comment by mokeyish** [comment]
@chmichael Does this error only occur in Windows MSVC? I see that Windows GNU has a compilation error, so Windows GNU does not apply this code.

https://github.com/mokeyish/smartdns-rs/actions/runs/11051683602/job/30702103661

**Comment by chmichael** [comment]
> @chmichael Does this error only occur in Windows MSVC? I see that Windows GNU has a compilation error, so Windows GNU does not apply this code.
> 
> https://github.com/mokeyish/smartdns-rs/actions/runs/11051683602/job/30702103661

Well i'm using the official rust compiler from https://www.rust-lang.org/tools/install and no error occured on my end.
I've applied your last change in net.rs '''#[cfg(all(target_os = "windows", target_env = "msvc"))]''' and compiled fine.

εικόνα

**Pull request merged**
