### PR TITLE
⬆️ Update byte-unit requirement from 4.0.17 to 5.0.3 #183 with fixed build

### PR DESCRIPTION
**Pull request by SamTV12345**

### CODE REVIEW

**Comment by SamTV12345** [comment]
@mokeyish I should be done with the upgrade of the byte crate.

**Comment by mokeyish** [comment]
LGTM, thank you!

**Comment by SamTV12345** [comment]
You're welcome. If you need help, feel free to ask. I just saw that dependabot pr and wanted to do some Rust coding so badly haha.

**Comment by mokeyish** [comment]
@SamTV12345 Yes, practice is the best way to learn Rust.  Recently I am planning to add restful api to smartdns.  To facilitate the subsequent addition of web UI.  I don't have much time, it may take a few months, if you are willing to help, you are very welcome 😊

**Comment by SamTV12345** [comment]
Sure I'll help you with that. Do we go with Actix, Rocket or Axum?

**Comment by mokeyish** [comment]
@SamTV12345 I updated that byte-unit #185 , MB and MiB are different.

**Pull request merged**
